[manifest]
version = "1.0.0"
dump_lua = true
priority = 5

#
# This manifest assumes the following release structure:
#
# BossBlindsBeat/
# ├─ BossBlindsBeat.json
# ├─ BossBlindsBeat.lua
# ├─ common.lua
# ├─ Init.lua
# ├─ LICENSE
# ├─ lovely.toml
# ├─ assets/
# ├─ bosses/
# ├─ localization/

[[patches]]
[patches.copy]
target = "globals.lua"
position = "append"
sources = [ "Init.lua" ]

[[patches]]
[patches.copy]
target = "main.lua"
<<<<<<< HEAD
=======
position = "append"
sources = [
  "BossBlindsBeat.lua"
]

[[patches]]
[patches.copy]
target = "functions/UI_definitions.lua"
>>>>>>> 6bbb3238cb0be8209e2a83af9320e1e694cff577
position = "append"
sources = [
  "BossBlindsBeat.lua"
]

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "G.GAME.stake > 1 and {"
position = "before"
match_indent = true
overwrite = false
payload = "CAL.BOSS.bosses_tab(),"
